(part "ISL83078EIBZA"
    (packageRef "SOIC127P600X175-8N")
    (interface
        (port "1" (symbPinId 1) (portName "RO") (portType INOUT))
        (port "2" (symbPinId 2) (portName "%RE%") (portType INOUT))
        (port "3" (symbPinId 3) (portName "DE") (portType INOUT))
        (port "4" (symbPinId 4) (portName "DI") (portType INOUT))
        (port "5" (symbPinId 5) (portName "GND") (portType INOUT))
        (port "6" (symbPinId 6) (portName "A/Y") (portType INOUT))
        (port "7" (symbPinId 7) (portName "B/Z") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VCC") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "968-ISL83078EIBZA")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Renesas-Intersil/ISL83078EIBZA?qs=dAsayXGOMrvZH4ftGSAhkg%3D%3D")
    (property "Manufacturer_Name" "Renesas Electronics")
    (property "Manufacturer_Part_Number" "ISL83078EIBZA")
    (property "Description" "The Intersil ISL8307XE are BiCMOS 3. 3V powered, single transceivers that meet both the RS-485 and RS-422 standards for balanced communication. These devices have very low bus currents (+125mA/-100mA), so they present a true 1/8 unit load to the RS-485 bus. This allows up to 256 transceivers on the network without violating the RS-485 specifications 32 unit load maximum, and without using repeaters. For example, in a remote utility meter reading system, individual meter readings are routed to a concentra")
    (property "Datasheet_Link" "https://www.renesas.com/en-us/www/doc/datasheet/isl83070e-71e-72e-73e-75e-78e.pdf")
    (property "symbolName1" "ISL83078EIBZA")
)
