(part "DMG1012T-13"
    (packageRef "SOT50P160X90-3N")
    (interface
        (port "1" (symbPinId 1) (portName "G") (portType INOUT))
        (port "2" (symbPinId 2) (portName "S") (portType INOUT))
        (port "3" (symbPinId 3) (portName "D") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "621-DMG1012T-13")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Diodes-Incorporated/DMG1012T-13?qs=w%2Fv1CP2dgqpw%252ByWBJOGGBA%3D%3D")
    (property "Manufacturer_Name" "Diodes Incorporated")
    (property "Manufacturer_Part_Number" "DMG1012T-13")
    (property "Description" "MOSFET 20V N-Ch Enhance Mode MOSFET")
    (property "Datasheet_Link" "https://www.diodes.com//assets/Datasheets/DMG1012T.pdf")
    (property "symbolName1" "DMG1012T-13")
)
