(part "CONSMA001-SMD-G-T"
    (packageRef "CONSMA001SMDGT")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "712-CONSMA001-SMD-GT")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/TE-Connectivity-Linx-Technologies/CONSMA001-SMD-G-T?qs=BJlw7L4Cy7%252BEXFff93cLJw%3D%3D")
    (property "Manufacturer_Name" "TE Connectivity")
    (property "Manufacturer_Part_Number" "CONSMA001-SMD-G-T")
    (property "Description" "Body Features: Body Material Brass | Body Plating Material Gold | Cable Connector Orientation Straight | Body Material Finish Plated | Configuration Features: Number of Coaxial Contacts 1 | Number of Positions 1 | PCB Mount Orientation Vertical | Contact Features: RF Connector Center Contact Plating Material Gold | RF Connector Center Contact Material Beryllium Copper | Electrical Characteristics: Impedance 50 OHM | Mechanical Attachment: RF Contact Captivation Method Mechanical | Detent Without | RF Connec")
    (property "Datasheet_Link" "https://www.te.com/commerce/DocumentDelivery/DDEController?Action=srchrtrv&DocNm=CONSMA001-SMD-G-T&DocType=Data%20Sheet&DocLang=English&PartCntxt=CONSMA001-SMD-G-T&DocFormat=pdf")
    (property "symbolName1" "CONSMA001-SMD-G-T")
)
