(part "TPS63021DSJR"
    (packageRef "SON50P300X400X100-15N-D")
    (interface
        (port "1" (symbPinId 1) (portName "VINA") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "FB") (portType INOUT))
        (port "4" (symbPinId 4) (portName "VOUT_1") (portType INOUT))
        (port "5" (symbPinId 5) (portName "VOUT_2") (portType INOUT))
        (port "6" (symbPinId 6) (portName "L2_1") (portType INOUT))
        (port "7" (symbPinId 7) (portName "L2_2") (portType INOUT))
        (port "8" (symbPinId 8) (portName "L1_1") (portType INOUT))
        (port "9" (symbPinId 9) (portName "L1_2") (portType INOUT))
        (port "10" (symbPinId 10) (portName "VIN_1") (portType INOUT))
        (port "11" (symbPinId 11) (portName "VIN_2") (portType INOUT))
        (port "12" (symbPinId 12) (portName "EN") (portType INOUT))
        (port "13" (symbPinId 13) (portName "PS/SYNC") (portType INOUT))
        (port "14" (symbPinId 14) (portName "PG") (portType INOUT))
        (port "15" (symbPinId 15) (portName "EP") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-TPS63021DSJR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TPS63021DSJR?qs=C44r%252BX3hXgL5uT9uesn8fg%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TPS63021DSJR")
    (property "Description" "High Efficiency Single Inductor Buck-Boost Converter with 4A Switch")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/tps63021")
    (property "symbolName1" "TPS63021DSJR")
)
