(part "FC0V104ZFTBR24"
    (packageRef "CAPAE1080X550N")
    (interface
        (port "1" (symbPinId 1) (portName "+") (portType INOUT))
        (port "2" (symbPinId 2) (portName "-") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "80-FC0V104ZFTBR24")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/KEMET/FC0V104ZFTBR24?qs=pfd5qewlna6EgB0gPZyt9Q%3D%3D")
    (property "Manufacturer_Name" "KEMET")
    (property "Manufacturer_Part_Number" "FC0V104ZFTBR24")
    (property "Description" "FC, Supercapacitors, SMD Can, 0.1 F, -20/+80%, 3.5 VDC, 70C, -25C, 70C, V-Chip, 0.09, 1 g, 10.5mm, 5.5mm, 10.8mm, 5mm")
    (property "Datasheet_Link" "https://content.kemet.com/datasheets/KEM_S6011_FC.pdf")
    (property "symbolName1" "FC0V104ZFTBR24")
)
