(part "TLV9304IDR"
    (packageRef "SOIC127P600X175-14N")
    (interface
        (port "1" (symbPinId 1) (portName "OUT1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "IN1-") (portType INOUT))
        (port "3" (symbPinId 3) (portName "IN1+") (portType INOUT))
        (port "4" (symbPinId 4) (portName "V+") (portType INOUT))
        (port "5" (symbPinId 5) (portName "IN2+") (portType INOUT))
        (port "6" (symbPinId 6) (portName "IN2-") (portType INOUT))
        (port "7" (symbPinId 7) (portName "OUT2") (portType INOUT))
        (port "8" (symbPinId 8) (portName "OUT3") (portType INOUT))
        (port "9" (symbPinId 9) (portName "IN3-") (portType INOUT))
        (port "10" (symbPinId 10) (portName "IN3+") (portType INOUT))
        (port "11" (symbPinId 11) (portName "V-") (portType INOUT))
        (port "12" (symbPinId 12) (portName "IN4+") (portType INOUT))
        (port "13" (symbPinId 13) (portName "IN4-") (portType INOUT))
        (port "14" (symbPinId 14) (portName "OUT4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-TLV9304IDR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TLV9304IDR?qs=P1JMDcb91o4JQ6%2FxIzVZ4Q%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TLV9304IDR")
    (property "Description" "Operational Amplifiers - Op Amps Quad 1MHz, 40-V, RRO, MUX-friendly operational amplifier for cost-sensitive systems 14-SOIC -40 to 125")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/tlv9304")
    (property "symbolName1" "TLV9304IDR")
)
