(part "3266X-1-203LF"
    (packageRef "3266X1203LF")
    (interface
        (port "1" (symbPinId 1) (portName "CCW") (portType INOUT))
        (port "2" (symbPinId 2) (portName "WIPER") (portType INOUT))
        (port "3" (symbPinId 3) (portName "CW") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "652-3266X-1-203LF")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Bourns/3266X-1-203LF?qs=%252B8v4bwhISUKQBVO7Xq7s8w%3D%3D")
    (property "Manufacturer_Name" "Bourns")
    (property "Manufacturer_Part_Number" "3266X-1-203LF")
    (property "Description" "Bourns 3266X Series 12-Turn Through Hole Cermet Trimmer Resistor with Pin Terminations, 20k +/-10% 1/4W +/-100ppm/C")
    (property "Datasheet_Link" "https://www.bourns.com/docs/Product-Datasheets/3266.pdf")
    (property "symbolName1" "3266X-1-203LF")
)
