(part "MMS9013-L-TP"
    (packageRef "SOT95P237X125-3N")
    (interface
        (port "1" (symbPinId 1) (portName "B") (portType INOUT))
        (port "2" (symbPinId 2) (portName "E") (portType INOUT))
        (port "3" (symbPinId 3) (portName "C") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "833-MMS9013L-TP")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Micro-Commercial-Components-MCC/MMS9013-L-TP?qs=P1JMDcb91o6OmgJiBYj6kQ%3D%3D")
    (property "Manufacturer_Name" "MCC")
    (property "Manufacturer_Part_Number" "MMS9013-L-TP")
    (property "Description" "Small Signal Bipolar Transistors")
    (property "Datasheet_Link" "https://mccsemi.com/pdf/Products/MMS9013(SOT-23).pdf")
    (property "symbolName1" "MMS9013-L-TP")
)
