(part "PJ-102B"
    (packageRef "PJ102B")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "490-PJ-102B")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Same-Sky/PJ-102B?qs=WyjlAZoYn50OhgyxNd%252BH3w%3D%3D")
    (property "Manufacturer_Name" "Same Sky")
    (property "Manufacturer_Part_Number" "PJ-102B")
    (property "Description" "2.5 x 6.5 mm, 2.5 A, Horizontal, Through Hole, Tapered Pins, Dc Power Jack Connector")
    (property "Datasheet_Link" "https://www.sameskydevices.com/product/resource/supplyframepdf/pj-102b.pdf")
    (property "symbolName1" "PJ-102B")
)
