(part "ESDALC6V1W5"
    (packageRef "SOT65P210X110-5N")
    (interface
        (port "1" (symbPinId 1) (portName "I/01") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "I/02") (portType INOUT))
        (port "4" (symbPinId 4) (portName "I/03") (portType INOUT))
        (port "5" (symbPinId 5) (portName "I/04") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "511-ESDALC6V1W5")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/STMicroelectronics/ESDALC6V1W5?qs=C%2FEejvvdwQ4xcyFnfrFaDw%3D%3D")
    (property "Manufacturer_Name" "STMicroelectronics")
    (property "Manufacturer_Part_Number" "ESDALC6V1W5")
    (property "Description" "TVS Diode Array Uni-Directional ESDALC6V1W5 Quad, 25W, SOT-323 5-Pin")
    (property "Datasheet_Link" "http://www.st.com/web/en/resource/technical/document/datasheet/CD00002946.pdf")
    (property "symbolName1" "ESDALC6V1W5")
)
